Enet4/faiss-rs

src/cluster.rs
src/error.rs
src/gpu.rs
src/index/flat.rs
src/index/gpu.rs
src/index/id_map.rs
src/index/io.rs
src/index/lsh.rs
src/index/mod.rs
src/lib.rs
src/macros.rs
src/selector.rs

- Replaced `faiss_try!` macro with a `faiss_try` function; using macros for error handling was only really necessary before the try operator, and should be an anti-pattern at this point.
- Removed the deprecated error description method: consumers should be printing errors via the `Display` impl.
- changed the visibility of `NativeError::from_last_error` to pub(crate), as it only makes sense for this crate to construct these errors.

Update error handling

---

src/error.rs
src/index/autotune.rs
src/index/mod.rs
troubleshooting.md

First steps to impl ParameterSpace

---

src/error.rs
src/index/gpu.rs

Should hopefully resolve #9. `to_gpu_multiple` becomes available to index implementations.

Multi GPU support

---

faiss-sys/src/bindings.rs
src/index/ivf_flat.rs
src/index/mod.rs

bindings.rs is from not released API.

[faiss v1.7.1] Added high-level IVFFlatIndex impl

---

faiss-sys/src/bindings.rs
faiss-sys/src/bindings_gpu.rs
src/gpu.rs

This updates both bindings.rs and bindings_gpu.rs in `faiss-sys` with Faiss 1.7.1, and makes the necessary changes for the library to build with the `gpu` feature.

Update bindings for Faiss 1.7.1

---

faiss-sys/src/lib.rs
src/index/mod.rs
src/index/scalar_quantizer.rs
src/macros.rs

bindings.rs by not released faiss API

[faiss v1.7.1] Add Index scalar quantizer

---

src/index/mod.rs
src/index/refine_flat.rs

fixes #18 
https://github.com/facebookresearch/faiss/pull/1821

[faiss 1.7.1] Impl RefineFlatIndex

---

src/index/flat.rs
src/index/ivf_flat.rs
src/index/lsh.rs
src/index/mod.rs

FlatIndexImpl
IVFFlatIndexImpl
LshIndex

Use impl_concurrent_index macro

---

src/index/flat.rs
src/index/ivf_flat.rs
src/index/mod.rs
src/index/pretransform.rs
src/index/refine_flat.rs
src/index/scalar_quantizer.rs

Add UpcastIndex trait

---

src/index/gpu.rs

IVFFlatIndexImpl
IVFScalarQuantizerIndexImpl

Impl to_gpu for new index types

---

src/index/flat.rs
src/index/ivf_flat.rs
src/index/lsh.rs
src/index/mod.rs
src/index/pretransform.rs
src/index/refine_flat.rs
src/index/scalar_quantizer.rs
src/macros.rs

Drop macro `impl_native_index_clone`
This is for generic code

Add TryClone trait

---

Cargo.toml
src/index/io.rs
src/index/io_flags.rs
src/index/mod.rs

I think using `pub mod const`s here achieves least surprise for users and minimizes boilerplate to make `enum` like a `bitmask`. (There's [this crate](https://github.com/Lukas3674/rust-bitmask-enum), and [this crate](https://docs.rs/bitflags/latest/bitflags/index.html), but it seems a lot just to make `enum` have something like [`impl BitOr`](https://doc.rust-lang.org/std/ops/trait.BitOr.html) / allow for "and"ing options.)
I could attempt to test this by creating a temporary index file and open it with these flags, too.
Not sure if you'd really want to version bump on this.

49 - allow read_index_with_flags for memory mapping some index types

---

src/index/flat.rs
src/index/id_map.rs
src/index/lsh.rs
src/index/mod.rs

Although some checks are made in this function, they are not enough to ensure memory safety: passing a dangling pointer is UB because dynamic casts still require dereferencing the pointer.

Make `TryFromInnerPtr::try_from_inner_ptr` unsafe

---

src/index/ivf_flat.rs

The following line is problematic as `std::os::raw::c_char` can either be `u8` or `i8` depending on the OS distribution.
I think it is possible to use `c_char` directly and avoid the issue.
What do you think?

fix: Use c_char instead of i8

---

src/index/id_map.rs

IndexImpl to IdMapIndex

---

.github/workflows/ci.yml

- Add `build-static` which builds and tests the crate with static linking
- Also update all jobs to use updated action steps

[CI] add build-static job

---

README.md
faiss-sys/build.rs
faiss-sys/gen_bindings.sh

- Update faiss submodule revision to latest `c_api_head`
- Tweak gen_bindings.sh
- Update build.rs to effectively support both features "static" and "gpu"
- Update README.md

Add GPU support to static linking

---

src/cluster.rs
src/index/autotune.rs
src/index/flat.rs
src/index/ivf_flat.rs
src/index/pretransform.rs
src/index/refine_flat.rs
src/index/scalar_quantizer.rs

- Reorganize imports
- Clippy lint fix: multiple_bound_locations

Reorganize imports & Clippy-fix

---

README.md

Hi!
I just wanted to add a small note to the build instructions to point mac users in the right direction. I had a rough time figuring out exactly where it needs to be placed on a mac to get picked up.

Add small note for mac users about dynlib location

---

.github/workflows/ci.yml

fix: usage of deprecated `Node.js 16` action

---

src/index/mod.rs

The method should taken `&mut self` from the beginning. Treating this as a breaking change though it's a bug. Fixes the error reported by Clippy.

Change signature of RangeSearchResult.distance_and_labels_mut
